<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Brand;
use App\Models\Category;
use App\Models\SubCategory;
use App\Models\Product;
use App\Models\Supplier;
use App\Models\District;
use App\Models\Upazilas;
use App\Models\Thana;
use App\Models\Location;
use App\Models\Customer;
use App\Models\Unit;
use App\Models\ExpenseType;
use App\Models\Expense;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Create Admin User
        $user = User::updateOrCreate(
            ['email' => 'admin@gmail.com'],
            [
                'name' => 'Admin',
                'mobile' => '01975-703216',
                'password' => Hash::make('12345678'),
                'otp' => '0',
                'status' => 'approved',
                'role' => 'admin',
            ]
        );

        // 2. Default Brand, Category, Unit
        $brand = Brand::firstOrCreate(
            ['name' => 'General'],
            ['status' => 'active', 'user_id' => $user->id]
        );

        $category = Category::firstOrCreate(
            ['category_name' => 'Sanitary'],
            ['status' => 'active', 'user_id' => $user->id]
        );

        $unit = Unit::firstOrCreate(
            ['unit_name' => 'Pcs'],
            ['status' => 'active', 'user_id' => $user->id]
        );

        $expenseType = ExpenseType::firstOrCreate(
            ['type_name' => 'Sallery'],
            ['status' => 'Active', 'user_id' => $user->id]
        );

        // 3. Products List from images
                                $productNames = [
            'Asian/Excellent pan',
            'Fabia/China Pan',
            'Batterfly Pan',
            'Litina Pan',
            'Aqua Pan',
            'Avro Pan',
            'Asian premimum pan',
            'Eva Basain',
            'Excellentt Comod',
            'Starling Big basin',
            'Starlling medium Basin',
            'Italia Combi comod',
            'Marco polo Cambri Comod',
            'Eros Combi Comod',
            'Signature Comod',
            'Grace Comod',
            'Elite Comod',
            'Taqua Basin',
            'Alma basin',
            'Flora Basin',
            'Polo Basin',
            'Nova Basin',
            'Westren basin',
            'Polo combri Comod',
            'Cairo Basin',
            'Victory Basin',
            'tornadro basin',
            'Ossis basin',
            'lavina Top basin',
            'Candy basin',
            'Arina Basin',
            'Simona Flat Urianal pan',
            'Opera basin',
            'China comod Millano',
            'China top basin',
            'Icon top basin',
            'Messio top Basin',
            '10"x10" Floor Drain',
            '12"x12" Floor Drain',
            '12"x12" SS Floor Drain Cuti',
            '18"x6" Design Shelf',
            '18"x5" Design Shelf',
            '24"x6" Design Shelf',
            'Stainless Steel Shelf',
            'Door Stopper Big',
            'Door Stopper Normal',
            'VIP Basin Mixer',
            'Plain Glass',
            'Plane Mirror (S)',
            'Plane Mirror (L)',
            'Plane Mirror (M)',
            'Toda Mirror',
            'Toda Mirror Oval shape',
            'Frame Mirror - M',
            'Concealed Shelf (W/O) legacy',
            'Concealed Shelf (NP/L/S)',
            'Concealed Shelf (Basket) 24"',
            'Concealed Shelf 18" (S/L/T)',
            'Concealed Shelf (O/S) 24"',
            '24"x6" Shelf Plain Glass',
            '24"x5" Shelf Plain',
            '24"x5" Shelf (O/S)',
            'Single Moving Shower Square (H)',
            'Moving Shower Square',
            'Moving Shower Heavy',
            'Moving Shower Star',
            'Moving Shower Round',
            'Moving Shower Sun',
            'LED Big Mirror',
            'LED Small Mirror',
            'Self Mirror',
            'Rose Angel Stop Cock',
            'Square Towel Rod',
            'Normal Basin-with-Mirror',
            'Model Big Mirror',
            'Model Small Mirror',
            'Dollar Mixer Top',
            'Glass Mirror',
            'Angel Stop Cock (3-Way)',
            'Angel Stop Cock Heavy',
            'Concealed Concealed (N/O/L)',
            'Concealed Concealed (Heavy/L)',
            'Concealed Concealed (Double/Heavy)',
            '0744 - 4 Concealed Concealed',
            '00112 Moving Outdoor Bath Tank Over',
            '00112 Moving Bath Tank Over Heavy',
            'Moving Filter Cock (NP)',
            'Paper Holder Antique M',
            'Soap Case 5x VIP Square',
            'Heavy Soap Cock',
            'Normal Soap Cock',
            'Soap Case SS Delta',
            'Soap Case SS Rose',
            'Soap Case SS - L',
            'Soap Case SS - (M)',
            'Soap Case SS Ring',
            'Soap Case Ring',
            '00556 Concealed Cock',
            '00556 Push Shower',
            '3-in-1 Pipe',
            'Liquid Dispenser (Touch) (S)',
            'Liquid Dispenser (Touch) (W/F)',
            'Liquid Dispenser (Push)',
            'China Hand Shower',
            'Toyo Push Shower',
            'Push Shower R. Up (Color)',
            'SS Single Towel Rod',
            'SS Double Towel Rod',
            'L Elbow',
            'Push Shower R. Up',
            'Push Shower R. Up (L)',
            'China Ceiling Shower',
            'CP Drain',
            '1/2" Short Band',
            '4" Pipe 1" Pipe',
            'Water Purifier',
            '0712 - Concealed Stopcock (NP/L/T)',
            '0744 - SS Concealed Stopcock',
            '0044 SS Concealed Stopcock',
            'Single Concealed',
            'Single Concealed Stop Cock',
            '00666 Concealed Stopcock (L/S)',
            '00333 Concealed Stopcock',
            'Solance Concealed (SS)',
            '0.5" Tee',
            '0.5" Plug',
            '0.5" Nipple 1" Pipe',
            '0.5" Elbow',
            '0.75" Elbow',
            '1" SS Pipe',
            '0.5" SS Pipe',
            '0.5" Socket',
            '0.75" Socket',
            '2" Thread',
            '0.5" Union',
            '0.5" Short Nipple',
            '0.5" Bush',
            '0.5" Cap TT',
            '0.75" Hex Nipple',
            '0.75" Reducer',
            '1" Reducer',
            '1" Plain Tee',
            '1" Plain Pipe',
            '4" Long Hinge',
            '4" Door Tail',
            '4" Plane Tail',
            '4" Solo Door Bolt',
            '18" Flat Towel Rod',
            'SS Corner Shelf',
            '12" Angel Rod',
            '0.75" Magic Pipe',
            '1.5" Magic Pipe',
            '1/2" Bib Cock',
            'SS Floor Drain (3-1)',
            'SS Big Cock (L-1)',
            'SS Moving Shower (L-1)',
            'SS Basin Stop Cock',
            'SS Handy Shower',
            'SS Plane Shower',
            'Dollar Push Shower',
            'Dollar Wall Shower',
            'SS Towel Rod',
            'Dollar Towel Holder',
            'Basin Ring',
            '30" Concealed Pipe (Stainless Steel)',
            'Rose Criteria Basin',
            '500 Liter Water Tank',
            '1" Teflon Concealed Tape (Roll)',
            'Super Angel Stop Cock',
            'Extra Heavy Pipe',
            'Basin Wash Basket',
            'Basin Waste (Stainless Steel)',
            'Basin Waste Plastic',
            'Basin Waste Coupling',
            'Zeeson 0.5" Bib Cock (L)',
            'Zeeson Push Shower',
            'Zeeson Basin Tap Light',
            'Zeeson Basin Tap Heavy',
            'Dollar Big Bib Cock',
            'Dollar Big Stop Cock',
            'Dollar Concealed Stop Cock',
            'Dollar Moving Shower (L-1)',
            'Dollar Moving Shower (Heavy)',
            'Dollar Moving Shower (L-2)',
            'Dollar Basin Stop Cock',
            'Dollar 0.5" Shower',
            'Zeeson Concealed Stop Cock',
            'SS Hand Shower',
            'Moving Filter Cock',
            '1" Teflon Tape',
            '4" Plain Pipe',
            '3" Pipe',
            '18*36 Astra Sink',
            '18*30 Astra Sink',
            '16*36 RFL Premimum Sink',
            '18*24 Delight Sink',
            '18*32 Delight Sink',
            '18*36 Daisy Sink',
            'Box mirror (A+B)',
            'Side Glass big',
            'Side Glass Small',
            'VIP Mirror',
            'Nupur glass',
            'Plano Mirror-1',
            'Plano Mirror-2',
            'Stone  Mirror CH',
            'Tiels Mirror',
            'Tiels Mirror Dubble',
            'Frame Mirror -M',
            'Guredreal Shelf  MPI-legacy',
            'Guredreal Shelf  MP-LG',
            'Guredreal Shelf  Rocket 21"',
            'Guredreal Shelf  PKK-10"',
            'Guredreal Wesda Shelf -6\'',
            '21-SS Shelf (H) New',
            '21-SS Shelf (H)',
            '21-SS Shelf (M)',
            '0747-Moving Shower Square CM',
            'Moving Shower Noman',
            'Moving shower mic-L',
            'Rosa angel stop call',
            'Square Tawal rod',
            'Normal Ambrush Mirror',
            'Nobo Big Mirror',
            'Nobo Small mirror',
            'Sattar Mixer Tap',
            'Mico West',
            'Angel Stop Cock (Grohe)',
            'Angel Stop Call Mpi',
            'Consel Big Cock Rizvi(H)',
            'Consel Big Cock Rristo_E',
            'Consel Big Cock Rizvi lever',
            '0744- Piller cock liver Cm',
            '00112-Moving Puiller cock Risvi liver',
            '00112-Moving Sink cock Risvi liver',
            'Moving Piller Cock MPI',
            'Paper Holder Aristro SS',
            'Shop Case Ss VIP Square',
            'Shope Case Ss -h',
            'Box Gally Pice',
            'Shop[ Case ss Bella',
            'Shop case Ss Rosa',
            'Shop case Ss -L',
            'Shop case Ss -(H)',
            'Shop case china',
            'Jally SS City',
            'Dubble Tawal rod-Cp',
            'Tawal rod Ss squarre',
            'A-1 Tape',
            'Liquid Shop case(Touch=M)',
            'Liquid Shop case(Touch=CP)',
            'Liquied Shop Case -m',
            'China low down',
            'Raya Push Shower',
            'Push Shower L -Cp Collor',
            'Trangel Tawal Rod',
            'SS Cikon Tawal Road',
            '1 " albow',
            'Rock Tawaril-B-M',
            'Rock tawaril-B-H',
            'China Silling Shower',
            'CP Brush',
            '1/2*3/4 R Soket',
            'Mirror Clips',
            'Korien Pudding',
            '0713- Consel Big cock MPI_T',
            '0708- 3/4\' Consel Stop cock',
            '0709-1\' Consel Stop call',
            'Had Shower',
            'Sorif Coscel Stop Call',
            'Solvent Cement Apson -500',
            'Solvent Cement -200',
            'Solvent Cement-100',
            '1.5" Ban',
            'in  Cap',
            '1.5 PVC Pipe',
            '4\' Cawal',
            '3/4" albow',
            '1" GI Tree',
            '3/4 GI Tree',
            '1" U Socket',
            '3/4 u Socket',
            '1\' Nippule',
            '3/4 Nippule',
            '1\' Socket',
            '1.5\' Albow',
            '1/2*3/4 Albow',
            '1.5; tree',
            '1.5*3/4 Tri',
            '1*1/2 R Socket',
            '1*3/4 R socket',
            '1\' Ball Valb',
            '3" Plane ban',
            '4" PVc Pipe',
            '1\' TS Pipe',
            '4\' long trap',
            '4" Door Tri',
            '4\' plane tri',
            '4"Side Door Ban',
            '20*16 Astra Sink',
            'RFL Corner Self',
            'RFL angel Valb',
            '1.25\' Magic Pipe',
            '1.5\' Magic pipe',
            'Rfl Sink cock',
            'RFL Wall tap m_1',
            'RFL Big Cock S-1',
            'RFL Moving Pillwer Cock',
            'RFL Round Shop Case',
            'RFL Frency Shower',
            'RFL Plane Shower',
            'Delex Push Shower',
            'Delex Wall Shower',
            'RFL tawal Rod',
            'Delex Tissue Holder',
            'Basin trey',
            '36\' Conection Pipe/RFL LIP PIPe',
            'Rosa Oriana basin',
            '500 Liter gaji Tank',
            '1\' Satter Consel Stop call',
            'Satter Angel stop call',
            'astra basin West',
            'Besin West Satter',
            'Rosa moving Piller Cock',
            'Rosa Moving sink tap',
            'Rosa Huil Big Cock_H',
            'Rosa Huil Big Cock_m',
            'Rosa Big cock liver',
            'Rosa Short Piller cock',
            'Satter cosel big cocks star',
            'Satter Big cock Delta',
            'Satter big cock Oliver',
            'Satter basin piller cock',
            'satter moving tap',
            'satter moving shower mic',
            'satter moving shower dalim',
            'satter Short liver piller cock',
            'satter eco angel stop call',
            'Satter 6\' Shower',
            'China full ambrush mirror',
            'SS tawal rod',
            'Moving sink cock',
            '1*3/4 Tri',
            '1*3/4 Albow',
            '18*36 RFL Premimum Sink',
            'satter moving Sink tap',
            'Moving sink cock MPI',
            'Akij Door Flash',
            'Neo Door one side Tamper',
            'Neo Door non Temper',
            'Full Aluminum Door',
            'Neo PvC Door',
            'N.M- Hot Stamp door',
            'N.M 3\' Door',
            'N.M 5" Door',
        ];

        \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
        Product::truncate();
        \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();

        foreach ($productNames as $index => $name) {
            Product::create([
                'product_name' => $name,
                'quantity' => '0',
                'cost_price' => '0',
                'sell_price' => '0',
                'status' => 'active',
                'product_code' => json_encode(['PRD-' . str_pad($index + 1, 4, '0', STR_PAD_LEFT)]),
                'brand_id' => $brand->id,
                'category_id' => $category->id,
                'unit_id' => $unit->id,
                'user_id' => $user->id,
            ]);
        }
    }
}
